---
title: "Bugs"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Feature 1, status: in progress

Factor MET intercept: Warning bij
Factor met covariaten en intercept: Ook warning
Meerdere factoren: Ook warning

## Bug 1, status: in progress
In the ANCOVA, .add_col adds a column to the right of the hypothesis matrix for each covariate. So the hypothesis matrix has the following columns:
Col1: Group1, Col2: Group2, Col3: Group3, Col4: Scalar that the constraint equates to, Col5: Covariate 1, Col6: Covariate2

I am a bit surprised that the scalar the constraint equates to ends up in the middle of the matrix. Is this correct? Shouldn't it be the last column? If you've programmed an exception into the fortran code to reorder these columns, how can I make sure not to trigger it?


## Bug 2, status: in progress

Even if the user specifies a different random seed, when the core Bain function is called, it is always set to 100 again:

Bain_chara<-paste0("Bain(estimate,covlist,grouppara=1,jointpara=jointpara,n=n,",IR_chara,"seed=100,print=FALSE)")

https://support.bioconductor.org/p/110439/


## Bug 3, status: in progress
Package installation fails, because the DLL is only built for x64
https://stackoverflow.com/questions/34744477/why-will-this-r-package-not-install-and-how-can-i-fix-it

## Bug 4, status: fix implemented
parse_hypotheses doesn't grab parameter names correctly. Consider adding a test to ensure that this is resolved.
